[userbot]
api_id = 1234567
api_hash = ''
admin_id = 0

[qiwi]
p2p_token = ''

[lolz]
xf_user = ''
xf_tfa_trust = ''
username = ''
userid = ''

[cryptocloud]
token = ''
shop_id = ''

[payment_settings]
time_check = 1800
